server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Проксирование запросов к PostgREST (для API)
    location /api/ {
        proxy_pass http://192.168.2.229:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Проксирование запросов к MinIO (для статики/изображений)
    location /minio/ {
        client_max_body_size 100M;
        # Используем внутренний IP/localhost, если MinIO на том же хосте
        proxy_pass http://192.168.2.229:31637/; 
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}